global:
  domain: vucongtuanduong.dpdns.org
  prefix: web-dev1

image:
  registry: docker.io
  repository: vucongtuanduong/web_grading_system/submission-service
  tag: "v1.0.0"
  pullPolicy: Always

spring:
  profilesActive: stg
  dbName: submission_db

service:
  type: ClusterIP
  port: 8082

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
