global:
  domain: vucongtuanduong.dpdns.org
  prefix: web-dev1

image:
  registry: docker.io
  repository: vucongtuanduong/web-grading-system-submission-service
  tag: "v1.3"
  pullPolicy: Always

spring:
  profilesActive: stg
  dbName: submission_db

rustfs:
  endpoint: http://rustfs:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: submission-files

service:
  type: ClusterIP
  port: 8082

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
